/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bkash_reader;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Sayeed
 */
public class dashboard extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        record_makeTable();
        refresh();
    }
    
   private void record_makeTable(){
        try{
            con = DBconnect.connect();
            pst = con.prepareStatement("select * from SMS_table");
            rs = pst.executeQuery();
            record_table.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            refresh();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
   
   private void customer_makeTable(){
        try{
            con = DBconnect.connect();
            pst = con.prepareStatement("select * from customer");
            rs = pst.executeQuery();
            customer_table.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
   
   private void refresh(){
       Calendar cal = new GregorianCalendar();
        int y = Calendar.YEAR;
        int m = Calendar.MONTH;
        int d = Calendar.DAY_OF_MONTH;
        String str = cal.get(y)+"-"+cal.get(m)+"-"+cal.get(d);
        date.setText("Date: "+str);
        
        try{
            con = DBconnect.connect();
            pst = con.prepareStatement("select * from SMS_table where Time='"+str+"'");
            rs = pst.executeQuery();
            
            while(rs.next()){
                String s = rs.getString("Sender");
                System.out.println(s+" "+str);
                pst = con.prepareStatement("update customer set status='Clear' where phone_no='"+s+"'");
                pst.execute();
            }
            pst.close();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
            //this.dispose();
        }
        customer_makeTable();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        record = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        record_table = new javax.swing.JTable();
        record_refresh = new javax.swing.JButton();
        customer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customer_table = new javax.swing.JTable();
        refresh_c = new javax.swing.JButton();
        remove_c = new javax.swing.JButton();
        add_c = new javax.swing.JButton();
        reset_c = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        search = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        search_table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        tid_sch = new javax.swing.JTextField();
        sender_sch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        search_sch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("bKash Payment System");
        setResizable(false);

        tab.setBackground(new java.awt.Color(204, 204, 255));
        tab.setToolTipText("Click on tabs to chose");
        tab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tab.setMinimumSize(new java.awt.Dimension(71, 26));
        tab.setName(""); // NOI18N
        tab.setPreferredSize(new java.awt.Dimension(784, 472));

        record.setBackground(new java.awt.Color(204, 204, 255));

        record_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        record_table.setToolTipText("Display all receved transactions");
        jScrollPane1.setViewportView(record_table);

        record_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkash_reader/Refresh.png"))); // NOI18N
        record_refresh.setText("Refresh");
        record_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                record_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recordLayout = new javax.swing.GroupLayout(record);
        record.setLayout(recordLayout);
        recordLayout.setHorizontalGroup(
            recordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordLayout.createSequentialGroup()
                .addGroup(recordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recordLayout.createSequentialGroup()
                        .addGap(629, 629, 629)
                        .addComponent(record_refresh))
                    .addGroup(recordLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        recordLayout.setVerticalGroup(
            recordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recordLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(record_refresh)
                .addGap(23, 23, 23))
        );

        tab.addTab("Record", record);

        customer.setBackground(new java.awt.Color(204, 204, 255));
        customer.setName(""); // NOI18N

        customer_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(customer_table);

        refresh_c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkash_reader/Refresh.png"))); // NOI18N
        refresh_c.setText("Refresh");
        refresh_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_cActionPerformed(evt);
            }
        });

        remove_c.setText("Remove");

        add_c.setText("Add New");
        add_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_cActionPerformed(evt);
            }
        });

        reset_c.setText("Re-set");
        reset_c.setToolTipText("Reset all customers's status");

        date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setToolTipText("Today");

        javax.swing.GroupLayout customerLayout = new javax.swing.GroupLayout(customer);
        customer.setLayout(customerLayout);
        customerLayout.setHorizontalGroup(
            customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(customerLayout.createSequentialGroup()
                        .addComponent(reset_c, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(add_c, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(remove_c, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refresh_c)))
                .addGap(25, 25, 25))
        );
        customerLayout.setVerticalGroup(
            customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerLayout.createSequentialGroup()
                        .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(refresh_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(remove_c, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(customerLayout.createSequentialGroup()
                        .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(add_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(customerLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reset_c, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tab.addTab("Customer", customer);

        search.setBackground(new java.awt.Color(204, 204, 255));

        search_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time", "Sender", "Amount", "Reference", "Counter", "TrnxID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(search_table);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        tid_sch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tid_sch.setToolTipText("Insert the transaction ID");

        sender_sch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sender_sch.setToolTipText("Insert the phone Number of Sender");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sender");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Trax ID");

        search_sch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkash_reader/search.png"))); // NOI18N
        search_sch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_schActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(search_sch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sender_sch, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(tid_sch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sender_sch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tid_sch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(search_sch, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
        search.setLayout(searchLayout);
        searchLayout.setHorizontalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        searchLayout.setVerticalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        tab.addTab("Search", search);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        tab.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void record_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_record_refreshActionPerformed
        record_makeTable();
    }//GEN-LAST:event_record_refreshActionPerformed

    private void search_schActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_schActionPerformed
        try{
            pst = con.prepareStatement("select * from SMS_table");
            rs = pst.executeQuery();

            String s = sender_sch.getText();
            String t = tid_sch.getText();
            
            boolean val=true;
            DefaultTableModel table = (DefaultTableModel) search_table.getModel();
            
            while(table.getRowCount()>0){
                for(int i=0;i<table.getRowCount(); i++){
                    table.removeRow(i);
                }
            }
            while(rs.next()){
                if(!t.equals("")){
                    if(rs.getString("TrxID").equals(t)){
                        table.addRow(new Object[]{rs.getString("Time"),rs.getString("Sender"),rs.getString("Amount"),rs.getString("Reference"),rs.getString("Counter"),rs.getString("TrxID")});
                        val = false;
                    }
                }
                if(!s.equals("")){
                    if(rs.getString("Sender").equals(s)){
                        table.addRow(new Object[]{rs.getString("Time"),rs.getString("Sender"),rs.getString("Amount"),rs.getString("Reference"),rs.getString("Counter"),rs.getString("TrxID")});
                        val = false;
                    }
                }
            }
            if(val){
                JOptionPane.showMessageDialog(null,"No Result Found On The Search");
            }
            rs.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_search_schActionPerformed

    private void add_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_cActionPerformed
        String n = JOptionPane.showInputDialog("Enter Customer's Name");
        String p = JOptionPane.showInputDialog("Enter "+n+"'s Phone Number");
        try{
            con = DBconnect.connect();
            pst = con.prepareStatement("insert into customer (phone_no,name) values (?,?)");

            pst.setString(1, p);
            pst.setString(2, n);
            pst.execute();
            pst.close();
            
            JOptionPane.showMessageDialog(null,"Record was added successfully");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
            
            customer_makeTable();
    }//GEN-LAST:event_add_cActionPerformed

    private void refresh_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_cActionPerformed
        refresh();
    }//GEN-LAST:event_refresh_cActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_c;
    private javax.swing.JPanel customer;
    private javax.swing.JTable customer_table;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel record;
    private javax.swing.JButton record_refresh;
    private javax.swing.JTable record_table;
    private javax.swing.JButton refresh_c;
    private javax.swing.JButton remove_c;
    private javax.swing.JButton reset_c;
    private javax.swing.JPanel search;
    private javax.swing.JButton search_sch;
    private javax.swing.JTable search_table;
    private javax.swing.JTextField sender_sch;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTextField tid_sch;
    // End of variables declaration//GEN-END:variables
}
